[package]
name = "linear-reg"
version = "0.1.0"
authors = ["AlbertoCaballero <albertocaballero80@outlook.com>"]
edition = "2018"

[lib]
name = "mlm"
path = "src/lib.rs"

[dependencies]
plotlib = "0.3.0"
